// ⚠ 產生檔——請勿手改。來源：tools/gen_hero_power_curve.mjs ＋ src/battle/moba/heroPowerCurveDerive.js
//   curve＝前期／中期／後期強度（1–5 分）；reasons＝推導依據（UI 顯示用）。
//   heroDatabase 不在模擬語意指紋內 ⇒ 推導結果以字面值落在這裡（此檔在指紋清單內），gate 以 --check 驗證沒有漂移。
export const HERO_POWER_CURVE_TABLE = Object.freeze({
  ironclad: Object.freeze({ curve: Object.freeze([3, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克","屬性成長偏低（前期）"]) }),
  thornwall: Object.freeze({ curve: Object.freeze([2.5, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克"]) }),
  ravager: Object.freeze({ curve: Object.freeze([3, 4.5, 4.5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士","屬性成長偏低（前期）","被動永久疊層（後期）"]) }),
  cinderfist: Object.freeze({ curve: Object.freeze([3.5, 4.5, 4]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士","屬性成長偏低（前期）"]) }),
  sting: Object.freeze({ curve: Object.freeze([4, 5, 3]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客","屬性成長偏高（後期）"]) }),
  duskblade: Object.freeze({ curve: Object.freeze([5, 5, 2]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客","屬性成長偏低（前期）"]) }),
  greymantle: Object.freeze({ curve: Object.freeze([3.5, 5, 3]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士","屬性成長偏高（後期）"]) }),
  embercoil: Object.freeze({ curve: Object.freeze([4.5, 5, 2]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士","屬性成長偏低（前期）"]) }),
  gambler: Object.freeze({ curve: Object.freeze([3, 5, 4]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）"]) }),
  auralith: Object.freeze({ curve: Object.freeze([3, 5, 4]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）"]) }),
  voidrift: Object.freeze({ curve: Object.freeze([4, 5, 3]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客","屬性成長偏低（前期）"]) }),
  razorwing: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客","屬性成長偏低（前期）","被動永久疊層（後期）"]) }),
  maestro: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）"]) }),
  phantom: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）"]) }),
  dawnstrike: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）"]) }),
  mirrorshot: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）"]) }),
  mantra: Object.freeze({ curve: Object.freeze([4.5, 4, 3.5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","屬性成長偏低（前期）"]) }),
  luminary: Object.freeze({ curve: Object.freeze([4, 4, 4]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）"]) }),
  stoneguard: Object.freeze({ curve: Object.freeze([3.5, 4, 4.5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","職業 坦克"]) }),
  hexweave: Object.freeze({ curve: Object.freeze([4, 4, 4]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）"]) }),
  suishan: Object.freeze({ curve: Object.freeze([2.5, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克"]) }),
  tixue: Object.freeze({ curve: Object.freeze([2.5, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克"]) }),
  kuangfeng: Object.freeze({ curve: Object.freeze([2.5, 4.5, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士","屬性成長偏高（後期）"]) }),
  rongyan: Object.freeze({ curve: Object.freeze([3.5, 4.5, 4]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士","屬性成長偏低（前期）"]) }),
  yueying: Object.freeze({ curve: Object.freeze([5, 5, 2]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客","被動伏擊上膛（前期）"]) }),
  dianguang: Object.freeze({ curve: Object.freeze([5, 5, 2]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客","屬性成長偏低（前期）"]) }),
  langwang: Object.freeze({ curve: Object.freeze([4.5, 5, 2]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士","屬性成長偏低（前期）"]) }),
  fengbao: Object.freeze({ curve: Object.freeze([4.5, 5, 2]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士","屬性成長偏低（前期）"]) }),
  shikong: Object.freeze({ curve: Object.freeze([3, 5, 4]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）"]) }),
  bingshuang: Object.freeze({ curve: Object.freeze([3, 5, 4]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）"]) }),
  anye: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客"]) }),
  jiansheng: Object.freeze({ curve: Object.freeze([2.5, 5, 4.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客","屬性成長偏高（後期）","被動永久疊層（後期）"]) }),
  xingchen: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏高（後期）","被動伏擊上膛（前期）"]) }),
  leiting: Object.freeze({ curve: Object.freeze([1.5, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏高（後期）"]) }),
  liuxing: Object.freeze({ curve: Object.freeze([2.5, 3, 4.5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏低（前期）"]) }),
  huanying: Object.freeze({ curve: Object.freeze([2.5, 3, 4.5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏低（前期）"]) }),
  shengguang: Object.freeze({ curve: Object.freeze([4, 4, 4]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）"]) }),
  dadi: Object.freeze({ curve: Object.freeze([3.5, 4, 4.5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","職業 坦克"]) }),
  tianshi: Object.freeze({ curve: Object.freeze([4, 4, 4]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）"]) }),
  fuwenbianzhi: Object.freeze({ curve: Object.freeze([4, 4, 4]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）"]) }),
  longji: Object.freeze({ curve: Object.freeze([3, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克","屬性成長偏低（前期）"]) }),
  xueyue: Object.freeze({ curve: Object.freeze([2.5, 4.5, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士","屬性成長偏高（後期）"]) }),
  tiemu: Object.freeze({ curve: Object.freeze([2, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克","屬性成長偏高（後期）"]) }),
  dushe: Object.freeze({ curve: Object.freeze([3, 4.5, 4.5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士"]) }),
  yingsi: Object.freeze({ curve: Object.freeze([4.5, 5, 2.5]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客"]) }),
  chichuan: Object.freeze({ curve: Object.freeze([4, 5, 2.5]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士"]) }),
  binghe: Object.freeze({ curve: Object.freeze([5, 5, 2]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客","屬性成長偏低（前期）"]) }),
  hunpo: Object.freeze({ curve: Object.freeze([3.5, 5, 3]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士","屬性成長偏高（後期）"]) }),
  leiming: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","屬性成長偏低（前期）"]) }),
  ronghuo: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","屬性成長偏低（前期）"]) }),
  miwu: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客","屬性成長偏高（後期）","被動伏擊上膛（前期）"]) }),
  jingxiang: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客"]) }),
  yanfeng: Object.freeze({ curve: Object.freeze([2.5, 3, 4.5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏低（前期）"]) }),
  hanbing: Object.freeze({ curve: Object.freeze([1.5, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏高（後期）"]) }),
  dujian: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）"]) }),
  liangzi: Object.freeze({ curve: Object.freeze([1.5, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏高（後期）"]) }),
  zhanchang: Object.freeze({ curve: Object.freeze([4.5, 4, 3.5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","屬性成長偏低（前期）"]) }),
  shiqiang: Object.freeze({ curve: Object.freeze([3, 4, 5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","職業 坦克","屬性成長偏高（後期）"]) }),
  fengshen: Object.freeze({ curve: Object.freeze([4.5, 4, 3.5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","屬性成長偏低（前期）"]) }),
  mingyun: Object.freeze({ curve: Object.freeze([3.5, 4, 4.5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","屬性成長偏高（後期）"]) }),
  xukong: Object.freeze({ curve: Object.freeze([3, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克","屬性成長偏低（前期）"]) }),
  longyi: Object.freeze({ curve: Object.freeze([2.5, 4.5, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士","被動永久疊層（後期）"]) }),
  tielian: Object.freeze({ curve: Object.freeze([3.5, 4.5, 4]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士","屬性成長偏低（前期）"]) }),
  shengdun: Object.freeze({ curve: Object.freeze([2.5, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克"]) }),
  yeiren: Object.freeze({ curve: Object.freeze([4.5, 5, 2.5]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客","屬性成長偏高（後期）","被動伏擊上膛（前期）"]) }),
  leisuhunter: Object.freeze({ curve: Object.freeze([4.5, 5, 2.5]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客"]) }),
  jingci: Object.freeze({ curve: Object.freeze([3.5, 5, 3]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士","屬性成長偏高（後期）"]) }),
  anliuyouXia: Object.freeze({ curve: Object.freeze([3.5, 5, 3]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士","屬性成長偏高（後期）"]) }),
  xingjie: Object.freeze({ curve: Object.freeze([2.5, 5, 4.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","屬性成長偏高（後期）"]) }),
  lieyan: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","屬性成長偏低（前期）"]) }),
  wuxing: Object.freeze({ curve: Object.freeze([3, 5, 4]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客","屬性成長偏高（後期）"]) }),
  hundun: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客"]) }),
  shensheng: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）"]) }),
  guangsu: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）"]) }),
  siwang: Object.freeze({ curve: Object.freeze([1.5, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏高（後期）"]) }),
  xuanfeng: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）"]) }),
  shiguang: Object.freeze({ curve: Object.freeze([4, 4, 4]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）"]) }),
  tiebi: Object.freeze({ curve: Object.freeze([3, 4, 5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","職業 坦克","屬性成長偏高（後期）"]) }),
  huanjing: Object.freeze({ curve: Object.freeze([4, 4, 4]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）"]) }),
  xuemai: Object.freeze({ curve: Object.freeze([3.5, 4, 4.5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","屬性成長偏高（後期）"]) }),
  tiankong: Object.freeze({ curve: Object.freeze([2.5, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克"]) }),
  ronggang: Object.freeze({ curve: Object.freeze([2.5, 4.5, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士","屬性成長偏高（後期）"]) }),
  bingshouweis: Object.freeze({ curve: Object.freeze([2, 4, 5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 坦克","屬性成長偏高（後期）"]) }),
  jufeng: Object.freeze({ curve: Object.freeze([3, 4.5, 4.5]), reasons: Object.freeze(["主路線 上路（Legacy 曲線 3/4/5）","職業 戰士"]) }),
  youming: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客","屬性成長偏高（後期）","被動永久疊層（後期）"]) }),
  shanying: Object.freeze({ curve: Object.freeze([5, 5, 2]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 刺客","屬性成長偏低（前期）"]) }),
  dadi2: Object.freeze({ curve: Object.freeze([3.5, 5, 3]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士","屬性成長偏高（後期）"]) }),
  leimingcf: Object.freeze({ curve: Object.freeze([4.5, 5, 2]), reasons: Object.freeze(["主路線 打野（Legacy 曲線 4/5/3）","職業 戰士","屬性成長偏低（前期）"]) }),
  mingyun2: Object.freeze({ curve: Object.freeze([2.5, 5, 4.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","屬性成長偏高（後期）"]) }),
  haixiao: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","屬性成長偏低（前期）"]) }),
  jueying: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客"]) }),
  guihuo: Object.freeze({ curve: Object.freeze([3.5, 5, 3.5]), reasons: Object.freeze(["主路線 中路（Legacy 曲線 3/5/4）","職業 刺客"]) }),
  tianfa: Object.freeze({ curve: Object.freeze([1, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏高（後期）","被動永久疊層（後期）"]) }),
  shengyan: Object.freeze({ curve: Object.freeze([2, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）"]) }),
  liangzicz: Object.freeze({ curve: Object.freeze([2.5, 3, 4.5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","屬性成長偏低（前期）"]) }),
  mori: Object.freeze({ curve: Object.freeze([1.5, 3, 5]), reasons: Object.freeze(["主路線 下路（Legacy 曲線 2/3/5）","被動永久疊層（後期）"]) }),
  shengming: Object.freeze({ curve: Object.freeze([4, 4, 4]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）"]) }),
  tieshixin: Object.freeze({ curve: Object.freeze([3.5, 4, 4.5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","職業 坦克"]) }),
  mingyunyindao: Object.freeze({ curve: Object.freeze([4.5, 4, 3.5]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）","屬性成長偏低（前期）"]) }),
  linghun: Object.freeze({ curve: Object.freeze([4, 4, 4]), reasons: Object.freeze(["主路線 輔助（Legacy 曲線 4/4/4）"]) }),
});
