import { GC, MONO } from "../../../ui/theme.js";

export const recapStyles = {
  shell: {
    width: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    background: GC.card,
    border: `1px solid ${GC.line}`,
    borderRadius: 12,
    marginBottom: 10,
    overflow: "hidden",
  },
  header: {
    padding: "16px 15px 17px",
    background: `linear-gradient(145deg, rgba(167,139,250,0.13), rgba(19,21,28,0.96) 58%)`,
  },
  kicker: {
    color: GC.purp,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: "0.2em",
  },
  headerMeta: {
    marginTop: 7,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 10,
    color: GC.gray,
    fontSize: 10,
  },
  team: {
    marginTop: 13,
    color: "#fff",
    fontSize: 23,
    fontWeight: 900,
    lineHeight: 1.15,
    overflowWrap: "anywhere",
  },
  summary: {
    marginTop: 8,
    color: GC.gold,
    fontSize: 15,
    fontWeight: 900,
    lineHeight: 1.35,
    overflowWrap: "anywhere",
  },
  section: {
    minWidth: 0,
    padding: "14px 15px 15px",
    borderTop: `1px solid ${GC.line}`,
  },
  sectionTitle: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 10,
    minWidth: 0,
    color: "#f4f4f5",
    fontSize: 13,
    fontWeight: 900,
    lineHeight: 1.3,
  },
  sectionHint: {
    color: GC.gray,
    fontSize: 9,
    fontWeight: 700,
    textAlign: "right",
    overflowWrap: "anywhere",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, auto)",
    alignItems: "start",
    gap: 12,
    minWidth: 0,
    padding: "8px 0",
    borderBottom: `1px solid ${GC.line}`,
  },
  rowLast: {
    borderBottom: "none",
  },
  label: {
    minWidth: 0,
    color: GC.gray,
    fontSize: 11,
    lineHeight: 1.4,
    overflowWrap: "anywhere",
  },
  value: {
    minWidth: 0,
    color: "#e5e7eb",
    fontSize: 11.5,
    fontWeight: 800,
    lineHeight: 1.4,
    textAlign: "right",
    overflowWrap: "anywhere",
  },
  monoValue: {
    fontFamily: MONO,
  },
  quiet: {
    marginTop: 9,
    color: GC.gray,
    fontSize: 11,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
  },
  accent: {
    color: GC.gold,
  },
  positive: {
    color: GC.green,
  },
  stops: {
    display: "grid",
    gap: 0,
    marginTop: 7,
    minWidth: 0,
  },
  stop: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(60px, auto) minmax(52px, auto)",
    alignItems: "start",
    gap: 8,
    minWidth: 0,
    padding: "8px 0",
    borderTop: `1px solid ${GC.line}`,
  },
  stopName: {
    minWidth: 0,
    color: "#e5e7eb",
    fontSize: 11,
    fontWeight: 800,
    lineHeight: 1.35,
    overflowWrap: "anywhere",
  },
  stopCell: {
    minWidth: 0,
    color: GC.gray,
    fontSize: 10.5,
    lineHeight: 1.35,
    textAlign: "right",
    overflowWrap: "anywhere",
  },
  stopPoints: {
    color: GC.green,
    fontFamily: MONO,
    fontWeight: 900,
  },
  cta: {
    width: "100%",
    boxSizing: "border-box",
    margin: 0,
    background: `linear-gradient(135deg, ${GC.purp}, #7c3aed)`,
    border: "none",
    borderRadius: 10,
    padding: "12px 10px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
  },
};

export const mergeStyles = (...styles) => Object.assign({}, ...styles);
